runtime: python311 # or another supported version

# instance_class: F2

entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8080

env_variables:
  MONGO_DB_USER: $MONGO_DB_USER
  MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
  MONGO_DB_DATABASE: $MONGO_DB_DATABASE
  MONGO_DB_URL: $MONGO_DB_URL
  OPEN_AI_API_KEY: $OPEN_AI_API_KEY

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto