runtime: python311 # or another supported version

# instance_class: F2

entrypoint: uvicorn src.main:app --host 0.0.0.0 --port 8080

env_variables:
  MONGO_DB_DATABASE: "database"
  MONGO_DB_URL: "mongodb+srv://ronny-admin:yRdcpABIyFKE0UKw@ronny-database.xaxm6tm.mongodb.net/?retryWrites=true&w=majority"
  OPEN_AI_API_KEY: "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"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
  http_headers:
    Access-Control-Allow-Origin: '*'