name: Deploy to App Engine

on:
  push:
    branches:
      - main # Change this to your main branch name
        june/test_secret

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: elice-hackathon
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Insert secrets
        uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          MONGO_DB_USER: ronny-admin
          MONGO_DB_PASSWORD: yRdcpABIyFKE0UKw
          MONGO_DB_DATABASE: database
          MONGO_DB_URL: mongodb+srv://ronny-admin:yRdcpABIyFKE0UKw@ronny-database.xaxm6tm.mongodb.net/?retryWrites=true&w=majority
        with:
          app_yaml_path: "app.yaml"

      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --quiet # Modify 'app.yaml' to your configuration file name
